directory: /Volumes/treasury/FLAC
library: /Volumes/treasury/FLAC/beets/flac-library.blb
ignore: .AppleDouble ._* *~ .DS_Store *.mp4 *.MP4 *.aac *.AAC *.m4a
art_filename: cover
threaded: yes

import:
    copy: yes
    write: yes
    resume: ask
    log: /Volumes/treasury/FLAC/beets/beets.arcadia.log
    autotag: no
    default_action: asis
    timid: yes

paths:
    default: $albumartist/$album%aunique{} ($year)/$track $artist - $year - $title
    singleton: Singles/$artist - $year - $title
    comp: Compilations/$album%aunique{} ($year)/$track $title

acoustid:
    apikey: 7HIrgs2T

fetchart:
    auto: yes
    maxwidth: 1600

# embedart:
#     ifempty: yes

scrub:
    auto: yes

duplicates:
    count: yes
    delete: no
    format: "$albumartist - $album ($year)"

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

web:
    host: 0.0.0.0
    cors: 'http://lossless.drewlustro.com'

plugins: fetchart fromfilename duplicates


