directory: /Volumes/treasury/FLAC
library: /Volumes/treasury/FLAC/beets/flac-library.blb
ignore: .AppleDouble ._* *~ .DS_Store *.mp4 *.MP4 *.aac *.AAC *.m4a
art_filename: cover
threaded: yes

# Standard configuration
import:
    log: /Volumes/treasury/FLAC/beets/beets.arcadia.log
    copy: yes
    write: yes
    resume: ask
    autotag: no
    default_action: asis
    timid: yes

# Repair library configuration
# import:
#     log: /Volumes/treasury/FLAC/beets/beets.arcadia.log
#     incremental: yes
#     incremental_skip_later: yes
#     resume: yes
#     move: no
#     copy: no
#     write: no
#     autotag: no
#     timid: yes

paths:
    default: $albumartist/$album ($year)/$track $artist - $year - $title
    singleton: Singles/$artist - $year - $title
    comp: Compilations/$album ($year)/$track $title

acoustid:
    apikey: 7HIrgs2T

fetchart:
    auto: yes
    maxwidth: 3200

scrub:
    auto: yes

duplicates:
    album: no
    checksum: ''
    copy: ''
    count: yes
    delete: no
    format: "$albumartist - $album ($year)"
    keys: ['length', 'bitrate', 'year']
    merge: no
    move: ''
    path: no
    strict: yes
    tag: ''

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

web:
    host: 0.0.0.0
    cors: 'http://lossless.drewlustro.com'

plugins: fetchart fromfilename duplicates


